Changes for user login functionality
vavs0208/sticky-notes pull request #4
Opened 2020-05-01 15:11 UTC by Tirtha1388

Changes for user login functionality-
1. Created method for adding new user.
2. Created method for authenticating login user.
3. Password encryption has been included.

2020-05-01 17:00 UTC, vavs0208 requested changes

2020-05-01 17:00 UTC, vavs0208 commented on src/main/java/com/stickynotes/dao/CreateUserDao.java
> +		userEntity.setPassword(hashPassword(userPojo.getPassword()));
Use model mapper

2020-05-01 17:00 UTC, vavs0208 commented on src/main/java/com/stickynotes/readservice/ReadController.java
> +	public boolean match(String passText,String passEncoded){
This piece of code belongs to business layer not in the Controller.
Request you to create a new BO layer and do the needful there

2020-05-01 17:00 UTC, vavs0208 commented on src/main/java/com/stickynotes/readservice/ReadController.java
> +				UserEntity userEntity= new UserEntity();
You are directly calling the entity layer inside the controller.
Please do this in DAO/ Business layer and refer it back to the controller

2020-06-13 14:34 UTC, Tirtha1388 commented
Closing and creating new pull request

2020-06-13 14:34 UTC, closed without merging